apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jialong-dev
  name: ingress-springboot-deployment
spec:
  selector:
    matchLabels:
      app: ingress-springboot-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: ingress-springboot-deployment
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ingress-springboot-deployment
        image: hongdada/com.huishi.demo:latest
        ports:
        - containerPort: 8080

---  
apiVersion: v1  
kind: Service  
metadata:  
  name: ingress-springboot-deployment
  namespace: jialong-dev
  labels:  
    app: ingress-springboot-deployment
spec:  
  ports:  
    - port: 8080  
      targetPort: 8080
  selector:  
    app: ingress-springboot-deployment